[WIP] Adding keng pytest to otg-examples
open-traffic-generator/otg-examples pull request #69
Opened 2024-04-04 22:43 UTC by dosarudaniel

2024-04-18 20:09 UTC, isgmano commented on snappi/pytest-examples/README.md
> +The goal of this repository is to help you setup, deploy and run test using Keysight Elastic Network Generator.
This is a too broad statement. There are other examples of how to use KENG as well. What is the specific usecase this example solves? Is this examples with pytest?

2024-04-18 20:40 UTC, isgmano commented on snappi/pytest-examples/README.md
> +5ac4e8831d8e   ghcr.io/open-traffic-generator/licensed/ixia-c-controller:latest   "./bin/controller --…"   4 seconds ago   Up 3 seconds             Ixia-c-Controller
what is the licensed controller?

2024-04-18 21:21 UTC, isgmano requested changes
Please resolve the comments. 
Mention what is unique in these examples and deployment.

2024-04-19 17:59 UTC, dosarudaniel commented on snappi/pytest-examples/py/test_unidirectional.py
These are performance high rate unidirectional, bidirectional and rfc2544 test scripts. The proposed files configures and deploy our Ixia-C DPDK based Traffic Generator.

2024-04-19 20:42 UTC, isgmano approved these changes

2024-04-19 21:44 UTC, bortok requested changes
@dosarudaniel could you please confirm that the plan is to use these scripts by @armdupre in his cloud-based dpdk lab example? asking because although you have diagrams, the readme is empty. so people would not be able to understand this contribution without an example that is using it.

also, could you please rename the subfolder from `pytest-examples` into `rfc2544` or `data-plane-performance`? I think your scripts are much more usable as is vs being a simple example

2024-04-19 22:11 UTC, armdupre approved these changes

2024-04-22 15:57 UTC, bortok requested changes
I made a few more notes, please address them before merging

2024-04-22 15:57 UTC, bortok commented on snappi/data-plane-performance/deployment/docker-compose.yaml
Please remove this file, has all sorts of artifacts internal to Keysight

2024-04-22 15:57 UTC, bortok commented on snappi/data-plane-performance/deployment/setup.sh
Do we need this, or will this be replaced by terraform lab setup?

2024-04-22 15:57 UTC, bortok commented on snappi/data-plane-performance/results/throughput_results_rfc2544_4_flows_upstream.json
do we need the results file?

2024-04-22 15:57 UTC, bortok commented on snappi/data-plane-performance/settings.json
please remove private IPs from the configuration file

2024-04-22 16:12 UTC, dosarudaniel commented on snappi/data-plane-performance/deployment/setup.sh
We need this, it is not related to terraform

2024-04-22 16:12 UTC, dosarudaniel commented on snappi/data-plane-performance/deployment/docker-compose.yaml
I removed the internal artifacts

2024-04-22 16:15 UTC, dosarudaniel commented on snappi/data-plane-performance/settings.json
Done.

2024-04-22 16:15 UTC, dosarudaniel commented on snappi/data-plane-performance/results/throughput_results_rfc2544_4_flows_upstream.json
Removed

2024-04-22 16:26 UTC, bortok commented on snappi/data-plane-performance/deployment/setup.sh
> +LICENSE_SERVER_VERSION="latest"
No longer used?

2024-04-22 16:28 UTC, dosarudaniel commented on snappi/data-plane-performance/deployment/setup.sh
> +LICENSE_SERVER_VERSION="latest"
Indeed, fixed

2024-04-22 16:33 UTC, bortok approved these changes

2024-04-22 17:32 UTC, merged