Ixia-c traffic engine deployment on Amazon Web Services with DPDK pull
open-traffic-generator/otg-examples pull request #73
Opened 2024-04-24 14:19 UTC by armdupre

Includes changes reviewed and approved by @dosarudaniel and @salsous.

2024-04-24 18:31 UTC, bortok commented on public-cloud/aws/ixia-c-dpdk-aws/README.md
> +## Prerequisites
Terraform is required to be installed, need to list this here

2024-04-24 18:32 UTC, bortok commented on public-cloud/aws/ixia-c-dpdk-aws/README.md
> +make all
```
time terraform apply -auto-approve
╷
│ Error: Failed to load plugin schemas
│
│ Error while loading schemas for plugin components: 5 problems:
│
│ - Failed to obtain provider schema: Could not load the schema for provider registry.terraform.io/hashicorp/aws: failed to instantiate provider
│ "registry.terraform.io/hashicorp/aws" to obtain schema: fork/exec
│ .terraform/providers/registry.terraform.io/hashicorp/aws/5.46.0/linux_amd64/terraform-provider-aws_v5.46.0_x5: invalid argument.
│ - Failed to obtain provider schema: Could not load the schema for provider registry.terraform.io/hashicorp/cloudinit: failed to instantiate provider
│ "registry.terraform.io/hashicorp/cloudinit" to obtain schema: fork/exec
│ .terraform/providers/registry.terraform.io/hashicorp/cloudinit/2.3.4/linux_amd64/terraform-provider-cloudinit_v2.3.4_x5: invalid argument.
│ - Failed to obtain provider schema: Could not load the schema for provider registry.terraform.io/hashicorp/http: failed to instantiate provider
│ "registry.terraform.io/hashicorp/http" to obtain schema: fork/exec
│ .terraform/providers/registry.terraform.io/hashicorp/http/3.4.2/linux_amd64/terraform-provider-http_v3.4.2_x5: invalid argument.
│ - Failed to obtain provider schema: Could not load the schema for provider registry.terraform.io/hashicorp/random: failed to instantiate provider
│ "registry.terraform.io/hashicorp/random" to obtain schema: fork/exec
│ .terraform/providers/registry.terraform.io/hashicorp/random/3.6.1/linux_amd64/terraform-provider-random_v3.6.1_x5: invalid argument.
│ - Failed to obtain provider schema: Could not load the schema for provider registry.terraform.io/hashicorp/time: failed to instantiate provider
│ "registry.terraform.io/hashicorp/time" to obtain schema: fork/exec
│ .terraform/providers/registry.terraform.io/hashicorp/time/0.11.1/linux_amd64/terraform-provider-time_v0.11.1_x5: invalid argument..
╵
```

2024-04-24 19:37 UTC, bortok requested changes
Requested changes:
* make it clear in the README to run all the steps in CloudShell
* add "git clone" and "cd" steps before "make all"
* if possible, throw an error if "make all" was run not in CloudShell

2024-04-24 22:20 UTC, isgmano reviewed
Please respond to the comments

2024-04-24 22:20 UTC, isgmano commented on snappi/data-plane-performance/configs/unidirectional.json
> +                            "value": "Agent2Eth1MacAddress"
Isn't this making it specific to AWS only? Same comment for all the changes made in this file for AWS specific requirements. Can this test still run standalone?

2024-04-24 22:20 UTC, isgmano commented on snappi/data-plane-performance/settings.json
> +    "localhost:5551",
Will this still run as standalone without AWS?

2024-04-25 23:27 UTC, isgmano approved these changes

2024-04-25 23:27 UTC, merged